pluginVersion=2.4.2
pluginDesc=Change inventory how you need
url=https://github.com/EndlessCodeGroup/RPGInventory

org.gradle.caching=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon.idletimeout=3600000
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.warning.mode=all


